SET TRANSACTION ISOLATION LEVEL
READ COMMITTED
BEGIN TRANSACTION TR
BEGIN TRY
UPDATE Person.Contact 
SET EmailAddress='jolyn@yahoo.com' 
WHERE ContactID = 1070

UPDATE HumanResources.EmployeeAddress SET AddressID = 32533 
WHERE EmployeeID = 1
COMMIT TRANSACTION TR

SELECT 'Transaction Executed'
END TRY
BEGIN CATCH
ROLLBACK TRANSACTION TR

SELECT 'Transaction Rollbacked'
END CATCH
